language: node_js
node_js:
  - 9

sudo: enabled
dist: trusty

branches:
  only:
    - master
    - develop
    - /^greenkeeper.*$/
    - /^dependency-update-.*$/

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - yarn install

script:
  - yarn run test
  - yarn run vcf
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  fqdn: maartenpaauw.com
  email: maartenpaauw@gmail.com
  name: "Maarten Paauw"
  on:
    branch: master
